apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-chat
  template:
    metadata:
      labels:
        app: myapp-chat
    spec:
      containers:
      - name: myapp-chat
        image: acr01custom01.azurecr.io/pubnub-chat-demo:latest
        ports:
        - containerPort: 80         
      imagePullSecrets:
      - name: acr-auth
