apiVersion: v1 
kind: Service
metadata:
  name: pubnub-chat-service
spec:
  type: LoadBalancer
  selector:
    app: myapp-chat            # ✅ Match the label from deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80           # ✅ FIXED HERE
